-
  name: 'Deploy Pre-Requisites'
  hosts: target3
  tasks:
    - name: 'Install FirewallD in host'
      yum:
        name: firewalld
        state: installed
    
    - name: 'Start FirewallD service'
      service:
        name: firewalld
        state: started
    - name: 'Enable FirewallD service'
      systemd:
        name: firewalld
        enabled: yes

-
  name: 'Deploy and Configure Database'
  hosts: target3
  user: root
  tasks:
    - name: 'Install MariaDB'
      yum:
        name: mariadb-server
        state: present
    - name: 'Start MariaDB service'
      service:
        name: mariadb
        state: started
    - name: 'Enable MariaDB service'
      systemd:
        name: mariadb
        enabled: yes
    - name: 'Configure firewall for Database'
      command: firewall-cmd --permanent --zone=public --add-port=3306/tcp
    - name: 'Reload firewall'
      systemd:
        name: firewalld
        state: reloaded

-
  name: 'Configure Database'
  hosts: target3
  user: osboxes
  tasks:
    - name: Create a new database with name 'ecomdb'
      mysql_db:
        name: ecomdb
        state: present
      register: db_created
    - name: Create user 'ecomuser'
      mysql_user:
        name: ecomuser
        host: localhost
        password: ecompassword
        priv: '*.*:ALL'
        state: present
    - name: Load Product Inventory Information to Database
      mysql_db:
        login_user: ecomuser
        login_password: ecompassword
        name: ecomdb
        target: ./db-load-script.sql

-
  name: Deploy and Configure Web
  hosts: target3
  tasks:
    - name: 'Install required packages'
      yum:
        name:
         - httpd
         - php
         - php-mysql
        state: present
    - name: 'Configure firewall for HTTP'
      command: firewall-cmd --permanent --zone=public --add-port=80/tcp
    - name: 'Reload firewall'
      systemd:
        name: firewalld
        state: reloaded
    - name: 'Configure httpd'
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regex: '^DirectoryIndex index.html'
        line: 'DirectoryIndex index.php'
        owner: root
        group: root
        mode: '0644'
    - name: 'Start httpd'
      service:
        name: httpd
        state: started
    - name: 'Enable HTTPd service'
      systemd:
        name: httpd
        enabled: yes
-
  name: 'Download code'
  hosts: target3
  tasks:
    - name: 'Install git'
      yum:
        name: git
        state: present
    - name: 'Clone repo'
      git:
        repo: 'https://github.com/kodekloudhub/learning-app-ecommerce.git'
        dest: /var/www/html
        force: yes
    - name: 'Update index.php'
      replace:
        path: /var/www/html/index.php
        regexp: '172\.20\.1\.101'
        replace: 'localhost'

